### ISSUE TITLE
Add RNA-seq dataset examples to modules that do not currently have an RNA-seq-specific example

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#110]
These added sections will be made into their own RNA-seq section and the original microarray dataset examples will be their own section. 

Here are the current modules that will need an RNA-seq version but currently only have a microarray example.
Each of these will need to get broken out into their own issue where we can discuss what datasets might be good to use for examples and details about what recommendations should be made but we can keep track of the progress here. 

Edit: as an overview, I'm going to mark which things we want to use non-QN'ed data and DEseq2 objects for vs QN'ed data. 

- [x] Clustering with RNA-seq data - non-QN'ed/DESeq2 #140 
- [x] Dimension reduction with RNA-seq data
     - [x] UMAP with RNA-seq data - non-QN'ed/DESeq2 #195  
     - [x] PCA with RNA-seq data - non-QN'ed/DESeq2 #196 
- [ ] Ortholog mapping with RNA-seq data #130 
- [ ] Pathway analysis with RNA-seq data #190

**Comment by jaclyn-taroni** [comment]
Many of these items will probably end up related to #103 !

**Comment by cansavvy** [comment]
As discussed here: https://github.com/AlexsLemonade/refinebio-examples/issues/103#issuecomment-656737302 we need to decide which of these example modules we want to use non-QN'ed data from refinebio and put into a DESeq2 object and which example modules we want to use refinebio QN'ed data directly. 

As a tangential question I may file as a separate issue, do we want to include any examples of multiple datasets QN'ed together from refinebio? This would be an example of where we might not want to use DESeq2 normalization.

**Comment by jaclyn-taroni** [comment]
I would argue that is a better fit for the “larger dataset” section mentioned in #102

**Comment by cansavvy** [comment]
I'm bringing over some discussion issue (#136) thoughts. 

- The default for RNA-seq modules is to use nonQN'ed data from refine.bio and [DESeq2 normalization workflow steps](https://github.com/AlexsLemonade/refinebio-examples/blob/d125ac7435cfd1cd1148abe25cc9f99808810a59/03-rnaseq/clustering_rnaseq_01_heatmap.Rmd#L220) which includes using `vst()` for most (maybe all?) instances.

This is a [nice explanation of both `rlog()` and `vst()`](http://master.bioconductor.org/packages/release/workflows/vignettes/rnaseqGene/inst/doc/rnaseqGene.html#the-variance-stabilizing-transformation-and-the-rlog). In short, they are similar and perform well. But `vst()` is much faster, so we should generally lean toward using it in our examples. Our users may not have much computing power, so I think its best to be cautious so it can run no matter what for them.
