### ISSUE TITLE
Update microarray analyses notebooks

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#173]
Although the content itself exists, our microarray analyses will need updating. 

Each analysis notebook will: 
- Have the getting started template material added to it(# 146)
- Be updated to adhere to the style guide (#148)
- Have its dataset added to the S3 bucket. (See https://github.com/AlexsLemonade/refinebio-examples/blob/master/CONTRIBUTING.md#adding-datasets-to-the-s3-bucket)
- Be added to the Snakefile and rendered with snakemake on the Docker container. 
- Be evaluated for any content changes that we may have updated thoughts on (this one we will have to determine analysis by analysis)

As of now here are the microarray notebooks that will need to be updated. We can break out each of these into their own issue to be discussed specifically. 

- [x] clustering_microarray_01_heatmap.Rmd #181 
- [x] differential_expression_microarray_01.Rmd #182 
- [x] dimension_reduction_microarray_01_pca.Rmd #196 
- [x] dimension_reduction_microarray_02_umap.Rmd #195 
- [ ] ortholog_mapping_microarray_01.Rmd #202 
<del> - [ ] pathway_analysis_microarray_01_ortholog_mapping_kegg.Rmd <\del> We likely don't need a separate orthlog mapping example now. Particularly if we use `msigdbr`
- [x] pathway_analysis_microarray_02_ora_with_webgestaltr.Rmd #206 
- [ ] pathway_analysis_microarray_03_qusage_meta_analysis.Rmd #215 
- [ ] pathway_analysis_microarray_04_qusage_replicate_vignette.Rmd #215
- [ ] pathway_analysis_microarray_05_qusage_single_dataset.Rmd #215 
- [ ] pathway_analysis_microarray_06_ssgsea.Rmd

**Comment by cansavvy** [comment]
As we revamp the notebooks, we should also keep in mind what are recurring questions/concepts that should be covered in the intro to microarray document #124. Questions that are tangential to the main analyses are the kind we'd link out to the intro document.  (Same as discussed for the intro to RNA-seq document).
